steps:
- id: docker build
  name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'gcr.io/$PROJECT_ID/ProposalService.V2:$SHORT_SHA', '.']
- id: docker push
  name: 'gcr.io/cloud-builders/docker'
  args: ['push', 'gcr.io/$PROJECT_ID/ProposalService.V2:$SHORT_SHA']
- id: Deploy to Cloud Run
  name: 'gcr.io/cloud-builders/gcloud'
  args:
  - run
  - deploy
  - ProposalService.V2
  - --image
  - gcr.io/$PROJECT_ID/ProposalService.V2:$SHORT_SHA
  - --region
  - us-central1
  - --platform
  - managed
  - --allow-unauthenticated

images:
- gcr.io/$PROJECT_ID/ProposalService.V2:$SHORT_SHA
